### ISSUE TITLE
Compiler warnings

### ISSUE THREAD

**Issue by florianhartig** [checcomi/threePGN-package#16]
Not sure about you guys, but I get a bunch of compiler warnings such as 

```
Warning: ‘countthinning’ may be used uninitialized in this function [-Wmaybe-uninitialized]
threePGN.f90:147:0:

     real(kind=8), allocatable, dimension(:,:) :: thinning
```

This is often not a problem, but maybe worth having a look at those, and ideally get rid of the warnings so that we don't miss important warnings during the compilation

**Comment by trotsiuk** [comment]
Those warnings are from the beginning and are mainly due to some undeclared or unused variables. Code need to be cleaned. We did part of it with special characters, etc.

**Comment by trotsiuk** [comment]
Moved to #17

**Comment by florianhartig** [comment]
But these compiler warnings are something completely different than the checks - these are simply unclean coding things that should be solved at some point

**Comment by florianhartig** [comment]
The CRAN checks don't flag the compiler warnings as warnings - I just see this in the compiler messages

**Comment by trotsiuk** [comment]
I think it will not pass the Trevis anyway with the compile warnings, or will it?
