### ISSUE TITLE
Solve CRAN check issues

### ISSUE THREAD

**Issue by florianhartig** [checcomi/threePGN-package#17]
see https://travis-ci.org/checcomi/threePGN-package

**Comment by florianhartig** [comment]
The first issue at the moment is that the vignette is loading packages that are not in the suggest of the package, which creates TRAVIS error

There are three options

- remove dplyr etc from the vignette
- add the packages to suggest
- add the packages to the TRAVIS setup 

I would favor option 1, to keep package dependencies to a minimum - is it really necessary to use dplyr and ggplot in the vignette?

**Comment by trotsiuk** [comment]
@florianhartig  I do agree, and the vignettes is now more for exploration and testing. I think it is too early for all the checks as we still writing the fortran code. And for testing it is easier with dplyr and ggplot. Once the script is ready we can reduce it to minimum.

**Comment by florianhartig** [comment]
hmm ... I would suggest to keep the package clean / operational, otherwise we can't use the automatic tests, plus you have to change everything later - why not to it right in the first place?

You can have additional manual tests / scripts, but those I usually place outside the main package, see e.g. https://github.com/florianhartig/DHARMa/tree/master/Code

**Comment by trotsiuk** [comment]
removed the dependencies to test 23a91d5558709ab1dd1c205b9577b7049ddb5b92
