### ISSUE TITLE
multisite runs

### ISSUE THREAD

**Issue by checcomi** [checcomi/threePGN-package#2]
@trotsiuk , the model can be run for multiple sites not only for 5, the number of sites depends on the rows of the siteData. 
We need to modify the weather inputs in a way that each site has a climID so the same weather can be used for multiple sites.

**Comment by checcomi** [comment]
@trotsiuk did you install the last version? in the previous version the noofSites was  dim(weather)[3]
reinstall the package and try again.

**Comment by checcomi** [comment]
@trotsiuk try now, I think I forgot to push the changes.
try also with siteData = siteData[1:2,]

**Comment by trotsiuk** [comment]
Works **perfect** @checcomi . Thank you much!
