### ISSUE TITLE
weatherID 

### ISSUE THREAD

**Issue by checcomi** [checcomi/threePGN-package#3]
Introduce weather ID in siteData to reduce the size of weather array and save memory.

**Comment by trotsiuk** [comment]
If I understood correctly, the weather id is currently referring to the order of the weather data in the three-dimensional array. I wonder if can introduce more an 'id' value (which can be either character or numeric), based on which we can link the site data and weather data.
like, climateId = c('vallis1', 'IUR3', ...)
