### ISSUE TITLE
Delete branches after pull request

### ISSUE THREAD

**Issue by florianhartig** [checcomi/threePGN-package#8]
@trotsiuk - after merging the pull request, you should delete the branch - there is an option for this in the pull request menu, or you can also delete here https://github.com/checcomi/threePGN-package/branches

**Comment by trotsiuk** [comment]
@florianhartig I agree this one of the option of working. You are too fast writing, I merged yesterday evening only.

**Comment by trotsiuk** [comment]
`DONE`
