### ISSUE TITLE
Travis CI admin

### ISSUE THREAD

**Issue by florianhartig** [checcomi/threePGN-package#9]
@checcomi you nee to give me admin rights so that I can enable the Travis CI checks, see https://stackoverflow.com/questions/25857012/is-it-possible-to-set-up-travis-for-a-project-for-which-you-are-a-collaborator

**Comment by checcomi** [comment]
@florianhartig as far as I understood for a user account there are only two levels (owner and collaborators).
https://help.github.com/articles/permission-levels-for-a-user-account-repository/
more levels are allowed only in organizations

Maybe I can try to enable Travis CI checks.

**Comment by florianhartig** [comment]
ok, then you have to do it! F

**Comment by florianhartig** [comment]
@checcomi, can you do the TRAVIS things - alternatively, we could move the repo to either PROFOUND or my working groups organization, then we're more flexible with the user rights.

**Comment by florianhartig** [comment]
@checcomi - sorry, getting an email about a failed test I just realized you already did this.

Solved

**Comment by checcomi** [comment]
Hey guys I'm completely new to Travis Ci, so I do not have a clear clue of what I'm doing. 
Please let me know if I need to do something or should we have a Skype?

**Comment by florianhartig** [comment]
No, it's all fine with TRAVIS, this works as it should - we just have a bunch of errors in the package that we should resolve. I have removed a few of them just now - see the rest at 

https://travis-ci.org/checcomi/threePGN-package
